### ISSUE TITLE
Passing authorization details from env vars?

### ISSUE THREAD

**Issue by holms** [jdxcode/npm-register#109]
Currently it's only reading auth details from htpasswd file? It's against 12factorapp and it doesn't scale, I need to build own container with htpasswd, instead of using your container (which actually absent on docker hub). That's not good :) I'm expecting to pass auth parameters via cli, or with env vars.

Might submit PR.

**Comment by jdxcode** [comment]
This is because the intention is for the users list to be dynamic data, not configuration. Ideally there should be a way to add/remove users at runtime with a web interface or CLI.

**Comment by holms** [comment]
I've actually ended up using docker secrets under docker swarm, which actually requires to have passwords in file (strange standard). Might be useful for someone.
