### ISSUE TITLE
Unsupported operation: `npm audit`

### ISSUE THREAD

**Issue by monkeyfuddle** [jdxcode/npm-register#118]
Running `npm audit` against rpm-register results in 

> npm ERR! code ENOAUDIT
> npm ERR! audit Your configured registry (http://YOUR_URL/) does not support audit requests.

It does a POST to the path
`/-/npm/v1/security/audits`

NPM version: 6.2.0

**Comment by dgautsch** [comment]
PR Open for this https://github.com/jdxcode/npm-register/pull/121

Still needs more test coverage.
