### ISSUE TITLE
Circle CI Access Key for AWS causes Failed Integration

### ISSUE THREAD

**Issue by dgautsch** [jdxcode/npm-register#126]
@jdxcode is there anything we can do about the Circle CI tests failing? I think they're linked to your AWS key yea? Is there anyway we can mock the responses from S3 or standup a neutral instance without your key?

**Comment by jdxcode** [comment]
yeah we rolled those creds at some point so they won't work anymore. I can't give out credentials to the internet so I'm not sure what the best course of action is. A way to stub it out would definitely be good.

We're no longer using npm-register though so I apologize but I won't be able to help much with this project.

**Comment by dgautsch** [comment]
Yea totally understand. I'll look into alternate solutions then. Thanks jdxcode.

**Comment by jdxcode** [comment]
Our security team did encounter a pretty big security issue with the project that would let people access any file on the host (specifically the htpasswd file). I put a patch in just now that should fix that.

**Comment by dgautsch** [comment]
Updated S3 credentials.
