### ISSUE TITLE
AWS > 2.304 Breaks Bluebird Promisify in NPM-Register

### ISSUE THREAD

**Issue by dgautsch** [jdxcode/npm-register#143]
See: https://github.com/aws/aws-sdk-js/issues/2229

**Comment by canercandan** [comment]
the issue #135 is also related, and I finally managed to fix it by setting this dependency with a fixed version:

```
"aws-sdk": "2.227.1"
```

**Comment by dgautsch** [comment]
@canercandan yea I see the issue now. Because we have the flag to update minor versions. It's a little annoying that AWS-sdk implemented a breaking change like that. I'll have to republish with a fixed version.

**Comment by dgautsch** [comment]
@canercandan I published v2.8.2 on npm. This should be compatible with s3

**Comment by canercandan** [comment]
@dgautsch awesome thanks for the heads-up
