### ISSUE TITLE
Configuring npm CLI to use new registry URL

### ISSUE THREAD

**Issue by zeke** [jdxcode/npm-register#29]
The README says to do this:

``` sh
npm update --registry http://urltomyregistry
```

But `npm help update` says:

> This command will update all the packages listed to the latest version (specified by the tag config), respecting semver.

Shouldn't the command be something like this instead?

``` sh
npm config set registry https://my-thing.herokuapp.com
```

**Comment by okeydoke** [comment]
Yeah I think that's a mistake in the README

**Comment by dickeyxxx** [comment]
Both are valid, we could add the other one to the README though

**Comment by dgautsch** [comment]
I think this has been resolved in the README, closing for now.
