### ISSUE TITLE
Webapp

### ISSUE THREAD

**Issue by pvieira91** [jdxcode/npm-register#33]
I'm used to sinopia but looks like that project is not being maintened. I installed npm-register just like your guide but I cannot access a webui with the list of modules. 
Does npm-register suports a web UI to search and view the npm modules?

**Comment by dickeyxxx** [comment]
No, this project does not have a web UI. I might accept a PR for one.

**Comment by dickeyxxx** [comment]
Definitely talk to me if anyone starts building this first though. It would be a lot of work and I want to make sure we get a good direction for it.

**Comment by ealves-pt** [comment]
@dickeyxxx I was actually thinking about building a UI with Vue.js for it.

That's why I've forked your project. 😄

**Comment by dickeyxxx** [comment]
Thinking about this a bit more, I've got some pretty specific ideas about how I want this to work. It might be better if I gave it a first pass to get the initial front-end framework up, then started accepting additions to it.

**Comment by pvieira91** [comment]
I'm available to help you guys. In mean time, I will have to stick with sinopia

**Comment by raininglemons** [comment]
@dickeyxxx Have you started on this? Else I'm keen, whether its as a plugin or to later be pulled in. Would probably do it with React...

**Comment by ransombriggs** [comment]
@raininglemons @dickeyxxx is taking time off until the end of the month, at which point he should be able to respond to this

**Comment by quickwind** [comment]
Any progress on this, guys?

**Comment by dickeyxxx** [comment]
Sadly it's falling pretty low on our priority list at the moment. If someone wanted to take a stab I'd be willing to take a look at a PR.

One suggestion on the implementation. It might be useful to export a JSON API that can list all of the packages. Then a front-end could render it but we could also reuse it for other things potentially.

**Comment by dickeyxxx** [comment]
My plan was to do it with a react app, but I'd be ok with whatever

**Comment by dgautsch** [comment]
I'll take a stab at this with react, noting your request for an API with all the packages listed out. Stay tuned.

**Comment by dgautsch** [comment]
Can we open a feature branch here called feature/ui so I can submit incremental PRs to it? That way you can review work as we go.

**Comment by jdxcode** [comment]
I'd rather you work on a fork, the main repo has access to some aws credentials used for the integration tests.

**Comment by dgautsch** [comment]
Ok so I have a working list of packages from disk, still need to work on s3. This is probably my unfamiliarity with how things are stored, but is there a way to discern your own packages versus cached public ones?

**Comment by jdxcode** [comment]
I don't believe so unfortunately. I'm open to adding that information somehow.

**Comment by dgautsch** [comment]
We now have the beginnings of a Web UI in v2.8.0. Closing.
