### ISSUE TITLE
Possibility to login from other source than htpasswd

### ISSUE THREAD

**Issue by throrin19** [jdxcode/npm-register#34]
Hi,

I check your project and I think, it's really good if we can login from external services (github, gitlab, ...) insteadof htpasswd file.

It's possible to add this with plugin or other part ?

**Comment by dickeyxxx** [comment]
All having an account does is let you publish packages. If we made it so anyone with an external account could login that would allow anyone to publish a package. It doesn't make sense with current functionality.

**Comment by sbuzonas** [comment]
It would be nice. Not necessarily allow all external users, but some sort of pluggable auth mechanism. I'm thinking about writing in cognito support.

**Comment by sbuzonas** [comment]
Is the auth pluggable now?
