### ISSUE TITLE
Tag Docker images per version

### ISSUE THREAD

**Issue by milankinen** [jdxcode/npm-register#63]
Hi!

We just started using our own private registry by using `dickeyxxx/npm-register` Docker image. However, we noticed that there is only `latest` tag in Dockerhub which worried our admins a little bit 'cause we can't ensure specific versions during our environment (re-)installations in future.

Could it be possible to start creating version tags per release to Dockerhub? If you see no problem in this setup, I can send a PR having e.g. `postpublish` script that does the Docker push and all necessary tagging based on project version found from `package.json`.

Any thoughts?

**Comment by dickeyxxx** [comment]
certainly willing to accept a PR

**Comment by lifeisfoo** [comment]
This can be done in your docker hub configuration page. Just add an [autobuild tag](https://docs.docker.com/docker-hub/builds/#add-and-run-a-new-build) that match (regex) your tags schema and it will be automatically triggered when you push a new tag on github. In this way, when you publish the v3.0.0 tag on github, also the 3.0.0 tag of your image is released on docker hub.

In your case it should be something like `/^v[0-9.]+$/`.

**Comment by holms** [comment]
This probably should be closed, this repo already has tags https://github.com/jdxcode/npm-register/tags therefore shouldn't be a problem to setup docker repo on docker hub

**Comment by milankinen** [comment]
Sure!
