### ISSUE TITLE
multiple registries and replication

### ISSUE THREAD

**Issue by twellspring** [jdxcode/npm-register#74]
Looking for a replacement for sinopia.  One issue I am having his how to managed multiple private registries.  Developers are publishing private packages in one location ( AWS staging VPC) and I want those new packages available in 2 other location (  AWS PROD VPC, AWS Failover VPC )

Is there a way to do this with npm-register.   rsync of the data directory kind of works with sinopia.

**Comment by dickeyxxx** [comment]
you could try rsyncing with the file storage method, not sure how well it would work but there isn't a central "registry" file or anything, it just attempts to see if the files exist before returning them so it should work in theory
