### ISSUE TITLE
heroku and s3 login failure

### ISSUE THREAD

**Issue by dgautsch** [jdxcode/npm-register#81]
Hoping I made a dumb mistake and this is easily resolved.

I'm having trouble logging into the registry I stood up on heroku. Here are the steps I've taken:

1. I've created an `htpasswd` file and uploaded it to my s3 instance in the root directory. The htpasswd file was created using the steps in the readme.
2. I then try to authenticate with `npm login --registry https://my-thing.herokuapp.com`
3. I receive a 401 response with the following error:

`invalid credentials : -/user/org.couchdb.user:myusername`

Did I miss something obvious?

Thanks for the help.

**Comment by dickeyxxx** [comment]
hmm. Maybe try verifying the password with `htpasswd -v file login`?

**Comment by dgautsch** [comment]
Hi dickey, I was able to verify the htpasswd file is correct. I'm wondering if this is an S3 configuration issue.

**Comment by dgautsch** [comment]
After further investigation I tried installing gulp via the registry with this command

`npm i gulp --save --registry=http://myregistry.herokuapp.com`

I looked in the papertrail logs and saw this:

`InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. `

**Comment by dgautsch** [comment]
Is this error because I'm using the wrong type of secret key? Or is this an issue with the code? Another thing I thought was peculiar was that when I try to checkout the code from heroku the repo is empty.... Maybe I need to try again.

**Comment by dgautsch** [comment]
Bumping this again. Is this something I'm doing wrong on AWS?

**Comment by jdxcode** [comment]
sorry but I have no idea why you're getting this error

**Comment by dgautsch** [comment]
Looks like the aws-sdk was out of date. Updating it fixed the issue. This was fixed in d29d059. Closing
