### ISSUE TITLE
node-gyp permissions issue with installing latest version (2.5.2)

### ISSUE THREAD

**Issue by jessebye** [jdxcode/npm-register#88]
On trying to install the latest version via `sudo npm install -g npm-register` (Ubuntu 14.04, Node 8.5.0) it hangs with:
```
**gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/npm-register/node_modules/bcrypt/.node-gyp/8.5.0"
**
```

This error continues to repeat indefinitely. Had to do a `npm config set unsafe-perm true` before I could complete the install.

**Comment by dgautsch** [comment]
I recommend changing your permissions with [this guide from NPM](https://docs.npmjs.com/getting-started/fixing-npm-permissions). You shouldn't be installing things as root unless you need to. Can you try changing your NPM permissions and reinstalling?

**Comment by jdxcode** [comment]
It's probably the bcrypt dependency, can you install that one by itself?

**Comment by jessebye** [comment]
@jdxcode confirmed it is `bcrypt`.

**Comment by dgautsch** [comment]
Closing this issue out as it was a environment issue.
