### ISSUE TITLE
Authenticate with official npm registry

### ISSUE THREAD

**Issue by Ianfeather** [jdxcode/npm-register#93]
Hi there!

We use a combination of public and private npm modules. We publish the private ones as `@scoped/packages` with `npm publish --access=restricted`.

I'd like to set up npm-register as a proxy in front of them but as far as I can tell there's no way to pass authentication details in the request to npm? I'm happy to add this feature if you'd take it, however i just wanted to double check that this isn't already possible? Have I just missed something obvious?

Thanks for your work with npm-registry!

**Comment by dgautsch** [comment]
@Ianfeather feel free to open a PR. I'm working on finishing up the front end UI and will move down the issue queue after that.
